version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Prabhjot-kaur-a1877033/spinnaker"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"